<link rel="stylesheet" href="./css2/styleadd.css">
<link rel="stylesheet" href="./css2/style.css">
<section class="h-100 bg-dark">
    <div id="ok" class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col">
          <div class="card card-registration my-4">
            <div class="row g-0">
              <div class="col-xl-6 d-none d-xl-block">
                
              <img src="./img2/pablo-heimplatz-ZODcBkEohk8-unsplash.jpg"
                  alt="Sample photo" class="img-fluid" id="img"
                  style="border-top-left-radius: .25rem; border-bottom-left-radius: .25rem; " />
              </div>
              <div class="col-xl-6">
                <form action="<?= $_SERVER['PHP_SELF'] ?>" method="post">
                <div class="card-body p-md-5 text-black">
                  <h3 class="mb-5 text-uppercase">Modifier un evenenment </h3>
  
                  <div class="row">
                  <div class="form-outline mb-4" >
                    <label class="form-label"  for="cin">id</label>
                    <input type="text" class="form-control" value="<?= $event['id'] ?>"  name="id" readonly >


                  </div>
  
                  <div class="form-outline mb-4">
                    <label class="form-label" for="Nom">Nom</label>
                    <input type="text" class="form-control" value="<?= $event['Nom'] ?>" id="Nom" name="Nom" >

                  </div>
  
                  <div class="form-outline mb-4">
                    <label class="form-label" for="Duree">Duree</label>
                    <input type="number" class="form-control" value="<?= $event['Duree'] ?>" id="Duree" name="Duree">
                  </div>
  
                  <div class="form-outline mb-4">
                    <label class="form-label" for="date_event">date_event </label>
                    <input type="date" class="form-control" value="<?= $event['date_event'] ?>" id="date_event" name="date_event">
                    
                  </div>
  
                  <div class="form-outline mb-4">
                    <label for="desc_event" class="form-label">desc_event</label>
                    <input type="text" class="form-control" value="<?= $event['desc_event'] ?>"  id="desc_event" name="desc_event" >
                  </div>

                  <div class="d-flex justify-content-end pt-3">
                    <button type="reset" class="btn btn-light btn-lg">Reset all</button>
                    <button type="submit" class="btn btn-warning btn-lg ms-2">Submit</button>
                  </div>
                </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
