<link rel="stylesheet" href="./css/styledetails.css" >
<div id="dsi" class="container py-4">
      <div class="row">
            <div class="col">
                <h3> Details de <?=$etud['nom'] ?> </h3>
            </div>
        </div> 

        <div id="card"class="card" style="width: 40rem;">
            
            <div class="card-body">
            <h5 class="card-title">Cin :</h5>
                <p class="card-text"><?=$etud['cin'] ?></p>
            <hr>
                <h5 class="card-title">Nom :</h5>
                <p class="card-text"><?=$etud['nom'] ?></p>
                <hr>
                <h5 class="card-title">Prenom :</h5>
                <p class="card-text"><?=$etud['prenom'] ?></p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><strong>Email: </strong><?=$etud['email'] ?></li>
                <li class="list-group-item"> <strong> Moyenne: </strong><?=$etud['moy'] ?></li>
                
            </ul>
            <div class="card-body">
            <a href="etudiant_edit.php?id=<?= $etud['cin'] ?>" class="btn btn-warning"><i class="bi bi-pencil-square"></i></a>
                            <!-- lien vers la page delete_todo.php -->
                            <a href="etudiant_delete.php?id=<?= $etud['cin'] ?>" class="btn btn-danger"><i class="bi bi-trash-fill"></i></a>
            </div>
        </div>
        
    </div>